### ISSUE TITLE
Knives support on Windows servers

### ISSUE THREAD

**Issue by Nereziel** [Nereziel/cs2-WeaponPaints#60]
On Windows servers, no knives are given.

**Comment by himenekocn** [comment]
I consulted some experts and ultimately came to the conclusion that the reason why Givenameditem can be used to spawn other knives on Linux is due to Linux Bug, while Valve correctly blocked this interface on Windows. Valve has added detection of limit items on Windows. It is uncertain whether this issue will be fixed on Linux in the future. Currently, in order to stably spawn other knives, subclasschange must be used.

**Comment by Nereziel** [comment]
Thank for the info, if you can get subclasschange working you can make a PR.
